[WOOR-34] feat: 초대 코드 생성 API 구현
prgrms-web-devcourse/Team-MusseukPeople-WooriMap-BE pull request #16
Opened 2022-07-30 08:00 UTC by yongsu-kang

## 요약
초대 코드 생성 API 구현
<br><br>

## 작업 내용
- couple 엔티티 nullable 추가
- InviteCode
  - 엔티티 생성
  - 서비스 생성
  - Response 생성
  - 테스트 코드 작성

- Couple
  - CoupleFacade 생성 -> InviteCode 서비스 추가
  - Couple 서비스만 생성
  - Couple Controller 생성

<br><br>

## 참고 사항
CoupleFacade에 대한 테스트는 징행하지 않았습니다.

Api 테스트에서 로그인 accessToken 저렇게 꺼내면 될지 여쭤보고 싶네요 ㅎㅎ

inviteCode 생성할 때 memberId 에 대한 존재 유무를 검사해야할까요??
<br><br>

2022-07-30 08:49 UTC, yuminhwan requested changes
마토 수고하셨습니다. 
몇가지 코멘트 남겼는 데 확인부탁드립니다~~

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
> +    private final CoupleService coupleService;
애는 Facade 안으로 들어가야 하지 않을까요?

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/inviteCode/application/InviteCodeService.java
> +package com.musseukpeople.woorimap.inviteCode.application;
저는 해당 도메인은 커플에서 밖에 안쓰이기 때문에 패키지가 커플안쪽으로 들어가야 한다고 생각하는 데 어떻게 생각하신가요?? 굳이 따로 빼낼 필요가 있을까요?

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/inviteCode/application/InviteCodeService.java
> +    private static final ThreadLocalRandom random = ThreadLocalRandom.current();
해당 코드 생성기는 클래스로 분리하는 게 좋을 것 같아요. 
그렇기 않으면 테스트도 어려워지고 ThreadLocalRandom에 너무 의존적? 인 것 같습니다. Service단에 `CodeGenerator` 같은 인터페이스로 빼고 Infrastructure에 `RandomCodeGenrator` 같이 생성하면 좀 더 느슨하게 결합될 것 같네요!

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/inviteCode/application/InviteCodeService.java
> +    }
메서드가 하나이기 때문에 한번 더 메서드로 묶을 필요는 없을 것 같아요. 
그냥 가져온 걸 한번 더 덮어쓰는 느낌? 이네용

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/inviteCode/application/InviteCodeService.java
> +    }
`orElse`를 사용하시면 있어도 로직이 실행되기 때문에 아마 save가 될 것 같습니다.
또한, 바로 리턴하는 것보단 조금 로직을 보기 쉽게 만들어 주시면 좋을 것 같아요.
지금 new 안에 다 들어가 있어서 읽기가 힘든 것 같습니다.

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/inviteCode/infrastructure/InviteCodQueryRepositoryImpl.java
> +    }
querydsl를 사용하신 이유가 있나요??

2022-07-30 08:49 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
> +    }
`로그인_토큰`을 사용해주세요!
후에 PR날릴 때 회원가입하면 토근 값 나오도록 변경하겠습니다.

2022-07-30 08:49 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/couple/presentation/CoupleControllerTest.java
> +    }
```suggestion
    private MockHttpServletResponse createInviteCodeApi() throws Exception {
return mockMvc.perform(post("/api/couples/invite")
                .header(HttpHeaders.AUTHORIZATION, accessToken))
            .andDo(print())
            .andReturn().getResponse();
    }
```

2022-07-30 08:49 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/inviteCode/infrastructure/InviteCodQueryRepositoryTest.java
> +    }
`@DataJpaTest`에 트랜잭션이 있기 때문에 불필요한 작업인 것 같습니다!

2022-07-30 08:49 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/inviteCode/infrastructure/InviteCodQueryRepositoryTest.java
> +        inviteCodeRepository.save(new InviteCode(INVITE_CODE, INVITER_ID, overExpireDate));
`BeforeEach`로 save를 먼저 해주는 것보단 해당 메서드에서 바로 expiredDate 된 코드를 save하는 것이 더 좋지 않을까요?

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
> +    private final CoupleService coupleService;
Facade 쓰기로 했으니깐 해당 서비스는 Facade로 들어가는 게 맞는 것 같습니다.

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/inviteCode/infrastructure/InviteCodQueryRepositoryImpl.java
> +@Repository
빈으로 안띄워도 되지 않나요??

2022-07-30 08:49 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/inviteCode/application/InviteCodeService.java
> +    }
사실 now()같은 로직이 테스트 할 수 없는 로직이라 어쩔 수 없긴 하지만 `createInviteCode` 파라미터로 LocalDateTime을 주입하는 방식으로 하면 테스트할 때 좀 더수월하지 않을까요? 
사실 저도 해보지는 않았지만 아래의 영상에서 테스트 할 수 있는 영역을 최대한 끌어올리라는 것에 공감해서 말씀드려봅니다. 
- [스프링캠프 2019 [Track 2 Session 3] : 무엇을 테스트할 것인가? 어떻게 테스트할 것인가? (권용근)](https://www.youtube.com/watch?v=YdtknE_yPk4)

2022-07-30 08:49 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
> +    private final CoupleService coupleService;
couple 서비스가 facade 안으로요?

2022-07-30 08:52 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/inviteCode/infrastructure/InviteCodQueryRepositoryImpl.java
> +    }
저는 querydsl이 직관적으로 보이는 거 같아서 사용했습니다 ㅎㅎ

2022-07-30 08:55 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/inviteCode/application/InviteCodeService.java
> +    private static final ThreadLocalRandom random = ThreadLocalRandom.current();
확실히 의존적인 거 같은 느낌이 있네요 ㅠㅠ

2022-07-30 08:55 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
> +    private final CoupleService coupleService;
넵넵 Controller 단에서는 Facade 하나만 의존하도록 하는 것이 좋지 않나 싶습니다.

2022-07-30 09:04 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
> +    private final CoupleService coupleService;
facade가 다른 도메인에서 사용될 기능을 모아두는 걸로 알고 있는 데 coupleService까지 들어간다면 의도가 좀 떨어지지 않을 까 생각되네요

2022-07-30 12:41 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/couple/presentation/CoupleController.java
> +    private final CoupleService coupleService;
그럼 facade에는 어떤걸 두고 service에 어떤걸 둘 생각이신거죠?

2022-08-01 04:01 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/inviteCode/infrastructure/InviteCodQueryRepositoryImpl.java
> +@Repository
안띄운다면 어떻게 처리할 수 있을까요??

2022-08-01 05:29 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/invitecode/infrastructure/InviteCodQueryRepositoryImpl.java
> +    private BooleanExpression inviterIdEq(Long inviterId) {
이 함수의 기능을 설명해주실 수 있으신가요??

2022-08-01 05:33 UTC, 78planet approved these changes, later dismissed
LGTM~

2022-08-01 05:50 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/invitecode/infrastructure/InviteCodQueryRepositoryImpl.java
> +    private BooleanExpression inviterIdEq(Long inviterId) {
초대자 Id 와 커플 초대 링크의 초대자 id 가 같은 지 판단해주는 메소드 입니닿ㅎ

2022-08-01 05:59 UTC, 78planet submitted a review, later dismissed
LGTM 💯

2022-08-01 06:21 UTC, yuminhwan approved these changes
마토 수고하셨습니다~~ 💯

2022-08-01 06:21 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/couple/infrastructure/RandomCodeGenerator.java
> +        String randomInviteCodeNumber = String.valueOf(random.nextInt(10000000) + 10000000);
매직넘버를 피하기 위해서 상수로 빼는 것이 좋아보이네요!
추가로 _를 붙여서 가독성 높여주면 좋겠습니다!

2022-08-01 06:21 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/util/RepositoryTest.java
> +public abstract class RepositoryTest {
어노테이션으로 바꿔도 될 것 같아요!
```suggestion
public @interface class RepositoryTest {
```

2022-08-01 06:27 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/couple/infrastructure/RandomCodeGenerator.java
> +        String randomInviteCodeNumber = String.valueOf(random.nextInt(10000000) + 10000000);
수정했는 데 commit이 늦었네요 ㅎㅎ

2022-08-01 06:28 UTC, yongsu-kang commented on src/test/java/com/musseukpeople/woorimap/util/RepositoryTest.java
> +public abstract class RepositoryTest {
확실히 어노태이션으로 하면 편하겠네요~?

2022-08-01 06:39 UTC, merged