[WOOR-37] feat: 게시글 생성 API 구현
prgrms-web-devcourse/Team-MusseukPeople-WooriMap-BE pull request #32
Opened 2022-08-03 09:43 UTC by 78planet

## 요약

게시글 생성 api 입니다. 

## 작업 내용
- 오직 커플만 게시글 생성을 할 수 있습니다. 
- post table, tag table, post_tag table 에 값을 입력합니다. 
- 중복된 tag는 tag table에 insert 하지 않고 새로운 tag만 tag table에 insert 합니다. 

## 참고 사항
- 지속적으로 코드 수정하도록 하겠습니다. 감사합니다.

2022-08-03 14:53 UTC, yuminhwan requested changes
윌 수고하셨습니다. 
코멘트 남겼으니 확인해주세요!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/couple/domain/Couple.java
> +    }
필요없는 생성자인 것 같습니다!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
> +    private final PostService postService;
사소하지만 저희 컨벤션으로 한칸은 띄우기로 했었습니다!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/PostFacade.java
> +        postService.createPostTag(savePostId, postTagIdList);
PostTag의 경우는 Post에서 생명주기를 관리하는 것이 좋아보입니다! 
persist 옵션으로 매핑해주면 좋을 것 같아요!!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
> +    }
public으로 열 필요는 없이 private로 설정하는 것이 좋아보입니다.
또한, stream으로 로직을 깔끔하게 만들 수 있을 것 같아요.

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/dto/CreatePostRequest.java
> +    }
해당 로직은 간단해서 굳이 dto에게 책임을 가지고 있을 필요가 있을까? 생각드네요. 현재는 dto에게 책임을 묻도록 하였지만 최대한 느슨하게 유지하는 게 좋을 것 같긴합니다.

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/entity/Post.java
> +    private BigDecimal longitude;
위, 경도는 한 세트이니 VO로 만들어 보면 어떨까요?

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/entity/Post.java
> +    private final List<PostImage> postImages = new ArrayList<>();
일급컬렉션으로 만들면 5장인지에 대한 유효성 검사를 일급컬렉션에게 책임을 줄 수 있을 것 같습니다. 후에 관련된 메서드도 안으로 들어가겠죠?

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/entity/Post.java
> +    }
postImage가 자신인지 확인할 필요가 있을까요? 저는 바꿔도 어차피 update문이 안나가서 확인할 필요가 없다고 생각하는 데 어떻게 생각하시나요?

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/entity/PostImage.java
> +    private String imagePath;
저는 imageUrl로 했는데 해당 컨벤션도 맞추면 좋을 것 같아요!!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/entity/PostImage.java
> +    public void setPost(Post post) {
set 메서드를 사용하는 것 보단 belongTo나 change 같은 메서드명을 사용하는 것이 좋아보입니다!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/entity/PostTag.java
> +    @ManyToOne(fetch = FetchType.LAZY)
JoinColumn은 명시적으로 있는 게 좋을 것 같습니다!!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
> +        return tagIdList;
디비를 사용한다면 저는 In절로 저장되어 있는 태그들을 가져고 오고 저장 되지 않은 태그들은 저장한뒤 합쳐서 주는 것이 로직이 깔끔해질 것 같습니다!!! 
한 가지 궁금한 점은 아이디 리스트로 반환하는 이유가 있을까요? 포스트랑 연관관계는 어떻게 맺나요??

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
> +    }
해당 로직은 stream으로 깔끔하게 만들 수 있을 것 같습니다!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
> +    @Transactional
클래스단에 read=only 트랙잭션이 있기 때문에 굳이 붙이지 않아도 될 것 같습니다!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
> +    public List<Tag> toTags(Couple couple, List<TagRequest> tagRequestList) {
해당 클래스에서만 사용한다면 private로 지정하는 것이 좋아보입니다!

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/tag/infrastructure/QueryTagRepositoryImpl.java
> +    }
Web에서 받은 Request를 인프라 쪽까지 가져와야 하나 싶네요. 😂

2022-08-03 14:53 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/tag/presentation/TagController.java
> +        List<Tag> tags = tagService.getTags();
Tag를 presentation 레이어까지 노출할 필요가 없어보입니다. DTO로 반환하는 것이 좋아보여요!

2022-08-03 14:53 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
저는 테스트간에 독립적으로 실행되어야 한다고 생각하는 데 해당 어노테이션을 쓰면 독립적이지 않게 되어 안좋다고 보는 데 어떻게 생각하시나요?

2022-08-03 14:53 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
> +        Long savedPostId = createPost(createCouple(), getCreatePostRequest());
given절에 커플이랑 포스트리퀘스트가 위치하게 되면 더 깔끔하지 않을까요?

2022-08-03 14:53 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
> +    void createTag_success() {
해당 메서드는 tagServiceTest에서 진행해야 되지 않을까요?

2022-08-03 14:53 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
> +        List<String> sampleImagePaths = Arrays.asList("http://wooriemap.aws.com/1.jpg", "http://wooriemap.aws.com/2.jpg");
```suggestion
        List<String> sampleImagePaths = List.of("http://wooriemap.aws.com/1.jpg", "http://wooriemap.aws.com/2.jpg");
```

2022-08-03 14:53 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
> +    }
멤버를 저장하지 않아 연관관계가 형성되지 않을 것 같습니다.

2022-08-03 15:06 UTC, yongsu-kang reviewed
재욱님 아주 고생많으셨습니다~~ 몇가지 커맨트 남겼습니다.

추가적으로 List에서 List로 변환하실 경우 스트림 쓰시면 코드 길이가 짧아지면서 깔끔해질 거 같아요~~~

2022-08-03 15:06 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
> +    }
```suggestion
    public List<PostTag> toPostTag(Long savePostId, List<Long> saveTagIdList) {
        return saveTagIdList.stream().map(tagId -> new PostTag(new Post(savePostId), new Tage(tagId));
    }
```

스트림으로 하면 깔끔해질 거 같아요~~

2022-08-03 15:06 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
> +        List<Tag> tagListFromDb = tagRepository.findExistTagByCoupleId(couple, tagRequestList);
tagRequestList를 바로 Repo로 보내는 것도 좋은 방법인 것 같아요.

저는 Request를 Repo까지 보내는 것 보단 필요한 데이터를 꺼내서 보내주는 편입니다.

List\<String\> tagNames로 넘겨주는 건 어떨까요?

2022-08-03 15:06 UTC, yongsu-kang commented on src/main/java/com/musseukpeople/woorimap/tag/infrastructure/QueryTagRepository.java
> +        List<TagRequest> tagList);
```suggestion
    List<Tag> findExistTagByCoupleId(Couple couple, List<TagRequest> tagList);
```

한 줄로 보면 기분 좋을 거 같아요~~

2022-08-03 15:06 UTC, yongsu-kang commented on src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
> +        coupleAccessToken = 로그인_토큰(new SignInRequest(user.getEmail(), user.getPassword()));
```suggestion
        coupleAccessToken = 커플_맺기_토큰(accessToken);
```

AcceptanceTest에 있어서 커플 맺고 다시 로그인 하지 않아도 되는 귀찮음을 제거했습니다 ㅎㅎ

2022-08-03 17:15 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
> +    }
감싸합니다~

2022-08-03 17:21 UTC, 78planet commented on src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
> +        coupleAccessToken = 로그인_토큰(new SignInRequest(user.getEmail(), user.getPassword()));
오 굿

2022-08-03 17:21 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
> +    }
귿 감사합니다~

2022-08-03 17:27 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/post/application/dto/CreatePostRequest.java
> +    }
dto 책임을 느슨하게 유지하는 방법이 어떤 것이 있을까요??

2022-08-03 17:50 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/post/entity/Post.java
> +    private final List<PostImage> postImages = new ArrayList<>();
이 부분에 대해서는 구두로 여쭤보겠습니다!

2022-08-03 18:14 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
> +        return tagIdList;
- 디비를 사용한다면 저는 In절로 저장되어 있는 태그들을 가져고 오고 저장 되지 않은 태그들은 저장한뒤 합쳐서 주는 것이 로직이 깔끔해질 것 같습니다!!!
    - -> 말씀하신 설명이 현재 이 코드인 것 같습니다.!
- 최종적으로 post와 연관된 tag id list 를 반환한 다음 Post Create 메소드 실행 시 PostTag 객체를 만들고 이 객체를 Post 와 연관시켜 줍니다!

2022-08-03 18:22 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/tag/presentation/TagController.java
> +        List<Tag> tags = tagService.getTags();
이 부분은 tag list 확인용으로 임시로 만들어 놓은 것입니다. 이 코드는 삭제하고 tag 조회 api 기능 구현할 때 상세하게 구현하겠습니당

2022-08-03 18:26 UTC, 78planet commented on src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
> +@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
각 테스트 케이스 간에 의존이 생겼을 때 order 를 사용했었는데, 지금은 각 테스트 케이스가 독립적으로 실행이 되어서 order는 사용안해도 될 것 같습니다!

2022-08-03 18:40 UTC, 78planet commented on src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
> +    void createTag_success() {
맞습니다만, createTag 메서드 자체가 게시글 생성 실행 시 하나의 트랜잭션에 묶인 메서드여서 하나의 test 파일에 있는 것이 기능적으로 보기도 편하고, 변수 등을 같이 공유하는게 많아서 하나의 파일에 넣었습니다.

2022-08-03 18:42 UTC, 78planet commented on src/test/java/com/musseukpeople/woorimap/post/application/PostServiceTest.java
> +    }
coupleService.createCouple 에서 멤버를 저장하지 않나요??

2022-08-03 18:42 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/tag/application/TagService.java
> +        List<Tag> tagListFromDb = tagRepository.findExistTagByCoupleId(couple, tagRequestList);
넵 그렇게 처리했습니다. 감사합니다~

2022-08-04 09:29 UTC, yongsu-kang approved these changes
LGTM~~

2022-08-04 09:30 UTC, yuminhwan approved these changes
일단 많이 늦어졌으니 후에 리팩토링하는 걸로 합시다~! 🔥🔥🔥🔥🔥

2022-08-04 09:31 UTC, merged