[WOOR-65] feat: 게시글 수정 API 구현
prgrms-web-devcourse/Team-MusseukPeople-WooriMap-BE pull request #47
Opened 2022-08-07 11:39 UTC by 78planet

## 요약

- 게시글 수정 API 기능 코드 입니다. 

## 작업 내용

- 게시글 수정 기능 추가하였습니다. 

## 참고 사항

- 지속적으로 코드 수정해나겠습니다. 감사합니다.

2022-08-07 13:29 UTC, yuminhwan requested changes
윌 수고하셨습니다. 
추가로 제가 post에 title이랑 content에 nullable을 추가 못했는 데 추가부탁드려요~~ 🎉🎉🎉

2022-08-07 13:29 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
> +    public Long modifyPost(List<Tag> list, EditPostRequest editPostRequest) {
```suggestion
    public Long modifyPost(List<Tag> tags, EditPostRequest editPostRequest) {
```
list보단 tags가 더 좋은 네이밍인 것 같습니다.

2022-08-07 13:29 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
> +    public Post getPostById(Long id) {
just ask : 해당 메서드는 테스트를 위해서 만드신건가요? 테스트를 위해서라면 삭제하는 것이 좋아보입니다

2022-08-07 13:29 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/dto/EditPostRequest.java
> +    private Long id;
id값을 body로 받는 것이 아닌 url의 path variable로 받는 것이 더 좋아보입니다.

2022-08-07 13:29 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/dto/EditPostRequest.java
> +    }
불필요한 메서드인 것 같습니다!

2022-08-07 13:29 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/domain/Post.java
> +    }
일급 컬렉션을 만들었는 데 굳이 get으로 꺼내서 할 필요없이 change라는 메서드를 만들어서 그 안에서 clear와 매핑을 해주는 것이 더 좋을 것 같습니다. 
만약 clear를 일급컬렉션에 넣게 된다면 add보단 change나 update  같은 네이밍이 더 어울려보이네요.

2022-08-07 13:29 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/domain/image/PostImages.java
> +    }
위에서 말했듯이 여기서 clear해주고 addAll 해주면 될 것 같아요. 메서드 네이밍은 수정이 필요할 것 같아요. 더하는 게 아니라 clear하고 더하게 되니.

2022-08-07 13:29 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/presentation/PostController.java
> +    @PutMapping
노션에도 PathVariable로 받도록 되어있습니다. ❌

2022-08-07 13:29 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/presentation/PostController.java
> +    public ResponseEntity<ApiResponse<Void>> modifyPost(@Valid @RequestBody EditPostRequest editPostRequest,
반환값을 줘야하는 지 안줘도 되는 지 프론트분들과 한번 이야기 해볼 필요가 있어보여요!

2022-08-07 13:29 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/application/PostFacadeTest.java
> +
PostFacade를 테스트 하기 위해 PostService를 가져올 필요가 있을 까요? 
굳이 확인하고 싶다면 return값을 response로 주거나 repository를 참조하는 것이 더 좋지 않을까요?

2022-08-08 01:09 UTC, 78planet commented on src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
> +    public Post getPostById(Long id) {
해당 메서드는 PostService의 modifyPost에서 post id 값으로 Post 엔티티를 가져올 때 사용합니다!

2022-08-08 05:03 UTC, yongsu-kang submitted a review, later dismissed
수고하셨습니다~~

2022-08-08 09:02 UTC, yuminhwan approved these changes, later dismissed
윌 수고하셨습니다!

2022-08-08 09:02 UTC, yuminhwan commented on config/infra/docker-compose.yml
> +#
지워주세요~~

2022-08-08 09:02 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/PostService.java
> +    }
노출할 필요가 없다면 최대한 노출안시키는 것이 좋아보입니다!

2022-08-08 09:02 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/application/PostFacadeTest.java
> +        assertThat(postId).isEqualTo(editPostId);
repository로 확인하면 좋겠네요! 진짜 바뀌었는지 확인해야 할 것 같아요,

2022-08-08 09:19 UTC, yuminhwan approved these changes
LGTM 💯💯💯

2022-08-08 09:20 UTC, merged