[WOOR-61] feat: 게시글 다건 조회 API 구현
prgrms-web-devcourse/Team-MusseukPeople-WooriMap-BE pull request #52
Opened 2022-08-08 09:48 UTC by yongsu-kang

## 요약
게시글 다건 조회 API 구현
<br><br>

## 작업 내용
- 제목, 태그로 검색기능 구현
- 필터가 없을 경우 전체 조회
- 페이징 사이즈 20으로 고정 정했음
- 태그 Response에 tagId 추가
<br><br>

## 참고 사항

<br><br>

2022-08-08 09:58 UTC, yuminhwan approved these changes, later dismissed
마토 수고하셨습니다.
쿼리 explain 한번 해보시면 좋을 것 같아요!

2022-08-08 09:58 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/dto/response/PostSearchResponse.java
> +    private String postThumbnailPath;
url로 통일시켜주세여!

2022-08-08 09:58 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/infrastructure/PostQueryRepositoryImpl.java
> +    }
쿼리 한번 explain으로 한번 확인해보면 좋을 것 같아요

2022-08-08 09:58 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/application/dto/response/PostSearchResponse.java
> +public class PostSearchResponse {
Swagger 추가해주세여~

2022-08-08 09:58 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/infrastructure/PostQueryRepositoryTest.java
> +@TestPropertySource(properties = "spring.jpa.properties.hibernate.default_batch_fetch_size=1000")
application-test.yml에 넣어주세요!

2022-08-09 02:31 UTC, yuminhwan requested changes
마토 수고하셨습니다. 
쿼리 한번 확인해주세요! 
like문은 explain으로 안뜨네요 왜지...?

2022-08-09 02:31 UTC, yuminhwan commented on src/test/java/com/musseukpeople/woorimap/post/presentation/PostControllerTest.java
> +        assertThat(posts).hasSize(savePostSize);
getResponseList 사용하시면 됩니다!

2022-08-09 02:31 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/infrastructure/PostQueryRepositoryImpl.java
> +                    post.title.as("imageUrl"),
title이 들어가면 안될 것 같습니다. 
전체값을 검증하는 테스트가 필요해 보여요!

2022-08-09 14:40 UTC, yuminhwan submitted a review, later dismissed
마토 수고하셨습니다!!

2022-08-09 14:40 UTC, yuminhwan commented on src/main/java/com/musseukpeople/woorimap/post/infrastructure/PostQueryRepositoryImpl.java
>              .on(tag.couple.id.eq(coupleId))
on절은 삭제해도 될 것 같아요!

2022-08-09 14:59 UTC, dbslzld15 approved these changes, later dismissed
LGTM!! 👍

2022-08-10 04:48 UTC, yuminhwan approved these changes, later dismissed
LGTM 💯

2022-08-10 04:58 UTC, 78planet approved these changes
LGTM 💯

2022-08-10 04:58 UTC, yuminhwan approved these changes
LGTM 🔥

2022-08-10 04:59 UTC, merged